import brazilCitiesByStateUfJson from "@/lib/brazilCitiesByStateUf.json";
export type StateItem = { value: string; text: string };

function sortByText(a: StateItem, b: StateItem) {
  return a.text.localeCompare(b.text);
}

function sortCities(a: string, b: string) {
  return a.localeCompare(b, "pt-BR");
}

export const STATES_BY_COUNTRY: Record<string, StateItem[]> = {
  Brazil: [
    { value: "AC", text: "Acre" },
    { value: "AL", text: "Alagoas" },
    { value: "AP", text: "Amapá" },
    { value: "AM", text: "Amazonas" },
    { value: "BA", text: "Bahia" },
    { value: "CE", text: "Ceará" },
    { value: "DF", text: "Distrito Federal" },
    { value: "ES", text: "Espírito Santo" },
    { value: "GO", text: "Goiás" },
    { value: "MA", text: "Maranhão" },
    { value: "MT", text: "Mato Grosso" },
    { value: "MS", text: "Mato Grosso do Sul" },
    { value: "MG", text: "Minas Gerais" },
    { value: "PA", text: "Pará" },
    { value: "PB", text: "Paraíba" },
    { value: "PR", text: "Paraná" },
    { value: "PE", text: "Pernambuco" },
    { value: "PI", text: "Piauí" },
    { value: "RJ", text: "Rio de Janeiro" },
    { value: "RN", text: "Rio Grande do Norte" },
    { value: "RS", text: "Rio Grande do Sul" },
    { value: "RO", text: "Rondônia" },
    { value: "RR", text: "Roraima" },
    { value: "SC", text: "Santa Catarina" },
    { value: "SP", text: "São Paulo" },
    { value: "SE", text: "Sergipe" },
    { value: "TO", text: "Tocantins" },
  ].sort(sortByText),
  Argentina: [
    { value: "Buenos Aires", text: "Buenos Aires" },
    { value: "CABA", text: "Ciudad Autónoma de Buenos Aires" },
    { value: "Catamarca", text: "Catamarca" },
    { value: "Chaco", text: "Chaco" },
    { value: "Chubut", text: "Chubut" },
    { value: "Córdoba", text: "Córdoba" },
    { value: "Corrientes", text: "Corrientes" },
    { value: "Entre Ríos", text: "Entre Ríos" },
    { value: "Formosa", text: "Formosa" },
    { value: "Jujuy", text: "Jujuy" },
    { value: "La Pampa", text: "La Pampa" },
    { value: "La Rioja", text: "La Rioja" },
    { value: "Mendoza", text: "Mendoza" },
    { value: "Misiones", text: "Misiones" },
    { value: "Neuquén", text: "Neuquén" },
    { value: "Río Negro", text: "Río Negro" },
    { value: "Salta", text: "Salta" },
    { value: "San Juan", text: "San Juan" },
    { value: "San Luis", text: "San Luis" },
    { value: "Santa Cruz", text: "Santa Cruz" },
    { value: "Santa Fe", text: "Santa Fe" },
    { value: "Santiago del Estero", text: "Santiago del Estero" },
    { value: "Tierra del Fuego", text: "Tierra del Fuego" },
    { value: "Tucumán", text: "Tucumán" },
  ].sort(sortByText),
  Canada: [
    { value: "AB", text: "Alberta" },
    { value: "BC", text: "British Columbia" },
    { value: "MB", text: "Manitoba" },
    { value: "NB", text: "New Brunswick" },
    { value: "NL", text: "Newfoundland and Labrador" },
    { value: "NS", text: "Nova Scotia" },
    { value: "NT", text: "Northwest Territories" },
    { value: "NU", text: "Nunavut" },
    { value: "ON", text: "Ontario" },
    { value: "PE", text: "Prince Edward Island" },
    { value: "QC", text: "Quebec" },
    { value: "SK", text: "Saskatchewan" },
    { value: "YT", text: "Yukon" },
  ].sort(sortByText),
  Chile: [
    { value: "Arica y Parinacota", text: "Arica y Parinacota" },
    { value: "Tarapacá", text: "Tarapacá" },
    { value: "Antofagasta", text: "Antofagasta" },
    { value: "Atacama", text: "Atacama" },
    { value: "Coquimbo", text: "Coquimbo" },
    { value: "Valparaíso", text: "Valparaíso" },
    { value: "Metropolitana de Santiago", text: "Metropolitana de Santiago" },
    { value: "O'Higgins", text: "O'Higgins" },
    { value: "Maule", text: "Maule" },
    { value: "Ñuble", text: "Ñuble" },
    { value: "Biobío", text: "Biobío" },
    { value: "La Araucanía", text: "La Araucanía" },
    { value: "Los Ríos", text: "Los Ríos" },
    { value: "Los Lagos", text: "Los Lagos" },
    { value: "Aysén", text: "Aysén" },
    { value: "Magallanes", text: "Magallanes" },
  ].sort(sortByText),
  Colombia: [
    { value: "Amazonas", text: "Amazonas" },
    { value: "Antioquia", text: "Antioquia" },
    { value: "Arauca", text: "Arauca" },
    { value: "Atlántico", text: "Atlántico" },
    { value: "Bolívar", text: "Bolívar" },
    { value: "Boyacá", text: "Boyacá" },
    { value: "Caldas", text: "Caldas" },
    { value: "Caquetá", text: "Caquetá" },
    { value: "Casanare", text: "Casanare" },
    { value: "Cauca", text: "Cauca" },
    { value: "Cesar", text: "Cesar" },
    { value: "Chocó", text: "Chocó" },
    { value: "Córdoba", text: "Córdoba" },
    { value: "Cundinamarca", text: "Cundinamarca" },
    { value: "Guainía", text: "Guainía" },
    { value: "Guaviare", text: "Guaviare" },
    { value: "Huila", text: "Huila" },
    { value: "La Guajira", text: "La Guajira" },
    { value: "Magdalena", text: "Magdalena" },
    { value: "Meta", text: "Meta" },
    { value: "Nariño", text: "Nariño" },
    { value: "Norte de Santander", text: "Norte de Santander" },
    { value: "Putumayo", text: "Putumayo" },
    { value: "Quindío", text: "Quindío" },
    { value: "Risaralda", text: "Risaralda" },
    { value: "San Andrés y Providencia", text: "San Andrés y Providencia" },
    { value: "Santander", text: "Santander" },
    { value: "Sucre", text: "Sucre" },
    { value: "Tolima", text: "Tolima" },
    { value: "Valle del Cauca", text: "Valle del Cauca" },
    { value: "Vaupés", text: "Vaupés" },
    { value: "Vichada", text: "Vichada" },
    { value: "Bogotá D.C.", text: "Bogotá D.C." },
  ].sort(sortByText),
  Mexico: [
    { value: "Aguascalientes", text: "Aguascalientes" },
    { value: "Baja California", text: "Baja California" },
    { value: "Baja California Sur", text: "Baja California Sur" },
    { value: "Campeche", text: "Campeche" },
    { value: "Chiapas", text: "Chiapas" },
    { value: "Chihuahua", text: "Chihuahua" },
    { value: "Coahuila", text: "Coahuila" },
    { value: "Colima", text: "Colima" },
    { value: "Durango", text: "Durango" },
    { value: "Guanajuato", text: "Guanajuato" },
    { value: "Guerrero", text: "Guerrero" },
    { value: "Hidalgo", text: "Hidalgo" },
    { value: "Jalisco", text: "Jalisco" },
    { value: "México", text: "México" },
    { value: "Michoacán", text: "Michoacán" },
    { value: "Morelos", text: "Morelos" },
    { value: "Nayarit", text: "Nayarit" },
    { value: "Nuevo León", text: "Nuevo León" },
    { value: "Oaxaca", text: "Oaxaca" },
    { value: "Puebla", text: "Puebla" },
    { value: "Querétaro", text: "Querétaro" },
    { value: "Quintana Roo", text: "Quintana Roo" },
    { value: "San Luis Potosí", text: "San Luis Potosí" },
    { value: "Sinaloa", text: "Sinaloa" },
    { value: "Sonora", text: "Sonora" },
    { value: "Tabasco", text: "Tabasco" },
    { value: "Tamaulipas", text: "Tamaulipas" },
    { value: "Tlaxcala", text: "Tlaxcala" },
    { value: "Veracruz", text: "Veracruz" },
    { value: "Yucatán", text: "Yucatán" },
    { value: "Zacatecas", text: "Zacatecas" },
    { value: "Ciudad de México", text: "Ciudad de México" },
  ].sort(sortByText),
  Portugal: [
    { value: "Aveiro", text: "Aveiro" },
    { value: "Beja", text: "Beja" },
    { value: "Braga", text: "Braga" },
    { value: "Bragança", text: "Bragança" },
    { value: "Castelo Branco", text: "Castelo Branco" },
    { value: "Coimbra", text: "Coimbra" },
    { value: "Évora", text: "Évora" },
    { value: "Faro", text: "Faro" },
    { value: "Guarda", text: "Guarda" },
    { value: "Leiria", text: "Leiria" },
    { value: "Lisboa", text: "Lisboa" },
    { value: "Portalegre", text: "Portalegre" },
    { value: "Porto", text: "Porto" },
    { value: "Santarém", text: "Santarém" },
    { value: "Setúbal", text: "Setúbal" },
    { value: "Viana do Castelo", text: "Viana do Castelo" },
    { value: "Vila Real", text: "Vila Real" },
    { value: "Viseu", text: "Viseu" },
    { value: "Açores", text: "Açores" },
    { value: "Madeira", text: "Madeira" },
  ].sort(sortByText),
  Spain: [
    { value: "Andalucía", text: "Andalucía" },
    { value: "Aragón", text: "Aragón" },
    { value: "Asturias", text: "Asturias" },
    { value: "Islas Baleares", text: "Islas Baleares" },
    { value: "Islas Canarias", text: "Islas Canarias" },
    { value: "Cantabria", text: "Cantabria" },
    { value: "Castilla-La Mancha", text: "Castilla-La Mancha" },
    { value: "Castilla y León", text: "Castilla y León" },
    { value: "Cataluña", text: "Cataluña" },
    { value: "Extremadura", text: "Extremadura" },
    { value: "Galicia", text: "Galicia" },
    { value: "La Rioja", text: "La Rioja" },
    { value: "Comunidad de Madrid", text: "Comunidad de Madrid" },
    { value: "Región de Murcia", text: "Región de Murcia" },
    { value: "Navarra", text: "Navarra" },
    { value: "País Vasco", text: "País Vasco" },
    { value: "Comunidad Valenciana", text: "Comunidad Valenciana" },
    { value: "Ceuta", text: "Ceuta" },
    { value: "Melilla", text: "Melilla" },
  ].sort(sortByText),
  "United Kingdom": [
    { value: "England", text: "England" },
    { value: "Scotland", text: "Scotland" },
    { value: "Wales", text: "Wales" },
    { value: "Northern Ireland", text: "Northern Ireland" },
  ].sort(sortByText),
  "United States": [
    { value: "AL", text: "Alabama" },
    { value: "AK", text: "Alaska" },
    { value: "AZ", text: "Arizona" },
    { value: "AR", text: "Arkansas" },
    { value: "CA", text: "California" },
    { value: "CO", text: "Colorado" },
    { value: "CT", text: "Connecticut" },
    { value: "DE", text: "Delaware" },
    { value: "FL", text: "Florida" },
    { value: "GA", text: "Georgia" },
    { value: "HI", text: "Hawaii" },
    { value: "ID", text: "Idaho" },
    { value: "IL", text: "Illinois" },
    { value: "IN", text: "Indiana" },
    { value: "IA", text: "Iowa" },
    { value: "KS", text: "Kansas" },
    { value: "KY", text: "Kentucky" },
    { value: "LA", text: "Louisiana" },
    { value: "ME", text: "Maine" },
    { value: "MD", text: "Maryland" },
    { value: "MA", text: "Massachusetts" },
    { value: "MI", text: "Michigan" },
    { value: "MN", text: "Minnesota" },
    { value: "MS", text: "Mississippi" },
    { value: "MO", text: "Missouri" },
    { value: "MT", text: "Montana" },
    { value: "NE", text: "Nebraska" },
    { value: "NV", text: "Nevada" },
    { value: "NH", text: "New Hampshire" },
    { value: "NJ", text: "New Jersey" },
    { value: "NM", text: "New Mexico" },
    { value: "NY", text: "New York" },
    { value: "NC", text: "North Carolina" },
    { value: "ND", text: "North Dakota" },
    { value: "OH", text: "Ohio" },
    { value: "OK", text: "Oklahoma" },
    { value: "OR", text: "Oregon" },
    { value: "PA", text: "Pennsylvania" },
    { value: "RI", text: "Rhode Island" },
    { value: "SC", text: "South Carolina" },
    { value: "SD", text: "South Dakota" },
    { value: "TN", text: "Tennessee" },
    { value: "TX", text: "Texas" },
    { value: "UT", text: "Utah" },
    { value: "VT", text: "Vermont" },
    { value: "VA", text: "Virginia" },
    { value: "WA", text: "Washington" },
    { value: "WV", text: "West Virginia" },
    { value: "WI", text: "Wisconsin" },
    { value: "WY", text: "Wyoming" },
    { value: "DC", text: "District of Columbia" },
  ].sort(sortByText),
};

const BRAZIL_CITIES_BY_STATE_UF = brazilCitiesByStateUfJson as Record<string, string[]>;

const BRAZIL_CITIES_BY_STATE: Record<string, string[]> = (STATES_BY_COUNTRY.Brazil || []).reduce<Record<string, string[]>>((acc, state) => {
  const cityList = [...(BRAZIL_CITIES_BY_STATE_UF[state.value] || [])].sort(sortCities);
  if (cityList.length === 0) return acc;

  acc[state.value] = cityList;
  acc[state.text] = cityList;
  return acc;
}, {});

export const CITIES_BY_COUNTRY_STATE: Record<string, Record<string, string[]>> = {
  Brazil: BRAZIL_CITIES_BY_STATE,
  "United States": {
    CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento"].sort(),
    NY: ["New York", "Buffalo", "Rochester", "Syracuse", "Albany"].sort(),
    TX: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"].sort(),
    FL: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"].sort(),
  },
  Canada: {
    ON: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton"].sort(),
    QC: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"].sort(),
    BC: ["Vancouver", "Surrey", "Burnaby", "Victoria", "Richmond"].sort(),
    AB: ["Calgary", "Edmonton", "Red Deer", "Lethbridge"].sort(),
  },
  Portugal: {
    Lisboa: ["Lisboa", "Loures", "Oeiras", "Amadora", "Sintra"].sort(),
    Porto: ["Porto", "Vila Nova de Gaia", "Matosinhos", "Maia"].sort(),
    Setúbal: ["Setúbal", "Almada", "Seixal", "Barreiro"].sort(),
    Braga: ["Braga", "Guimarães", "Barcelos"].sort(),
    Faro: ["Faro", "Portimão", "Olhão", "Loulé"].sort(),
  },
  Spain: {
    "Comunidad de Madrid": ["Madrid", "Alcalá de Henares", "Móstoles", "Getafe", "Fuenlabrada"].sort(),
    Cataluña: ["Barcelona", "L'Hospitalet de Llobregat", "Badalona", "Tarragona", "Girona"].sort(),
    Andalucía: ["Sevilla", "Málaga", "Córdoba", "Granada", "Cádiz"].sort(),
    "Comunidad Valenciana": ["Valencia", "Alicante", "Castellón de la Plana", "Elche"].sort(),
  },
  Mexico: {
    "Ciudad de México": ["Ciudad de México"].sort(),
    Jalisco: ["Guadalajara", "Zapopan", "Tlaquepaque"].sort(),
    "Nuevo León": ["Monterrey", "San Nicolás de los Garza", "Guadalupe"].sort(),
    "México": ["Toluca", "Ecatepec de Morelos", "Naucalpan de Juárez"].sort(),
    Puebla: ["Puebla", "Tehuacán"].sort(),
  },
  Argentina: {
    "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil"].sort(),
    CABA: ["Buenos Aires"].sort(),
    Córdoba: ["Córdoba", "Villa Carlos Paz", "Río Cuarto"].sort(),
    Mendoza: ["Mendoza", "San Rafael"].sort(),
    "Santa Fe": ["Rosario", "Santa Fe"].sort(),
  },
  Chile: {
    "Metropolitana de Santiago": ["Santiago", "Puente Alto", "Maipú"].sort(),
    Valparaíso: ["Valparaíso", "Viña del Mar"].sort(),
    Biobío: ["Concepción", "Talcahuano"].sort(),
  },
  Colombia: {
    "Bogotá D.C.": ["Bogotá"].sort(),
    Antioquia: ["Medellín", "Bello", "Itagüí"].sort(),
    "Valle del Cauca": ["Cali", "Palmira"].sort(),
    Atlántico: ["Barranquilla", "Soledad"].sort(),
  },
};

function uniqueStrings(items: string[]) {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item)) return false;
    seen.add(item);
    return true;
  });
}

export function getCountryCities(country: string, stateValue?: string, stateName?: string) {
  const normalizedCountry = String(country || "").trim();
  const byCountry = CITIES_BY_COUNTRY_STATE[normalizedCountry] || {};

  const listByCode = stateValue ? (byCountry[String(stateValue).trim()] || []) : [];
  const listByName = stateName ? (byCountry[String(stateName).trim()] || []) : [];
  return uniqueStrings([...listByCode, ...listByName]);
}
