export type StateItem = { value: string; text: string };

export const STATES_BY_COUNTRY: Record<string, StateItem[]> = {
  Brazil: [
    { value: "AC", text: "Acre" },
    { value: "AL", text: "Alagoas" },
    { value: "AP", text: "Amapá" },
    { value: "AM", text: "Amazonas" },
    { value: "BA", text: "Bahia" },
    { value: "CE", text: "Ceará" },
    { value: "DF", text: "Distrito Federal" },
    { value: "ES", text: "Espírito Santo" },
    { value: "GO", text: "Goiás" },
    { value: "MA", text: "Maranhão" },
    { value: "MT", text: "Mato Grosso" },
    { value: "MS", text: "Mato Grosso do Sul" },
    { value: "MG", text: "Minas Gerais" },
    { value: "PA", text: "Pará" },
    { value: "PB", text: "Paraíba" },
    { value: "PR", text: "Paraná" },
    { value: "PE", text: "Pernambuco" },
    { value: "PI", text: "Piauí" },
    { value: "RJ", text: "Rio de Janeiro" },
    { value: "RN", text: "Rio Grande do Norte" },
    { value: "RS", text: "Rio Grande do Sul" },
    { value: "RO", text: "Rondônia" },
    { value: "RR", text: "Roraima" },
    { value: "SC", text: "Santa Catarina" },
    { value: "SP", text: "São Paulo" },
    { value: "SE", text: "Sergipe" },
    { value: "TO", text: "Tocantins" },
  ],
  Argentina: [
    { value: "Buenos Aires", text: "Buenos Aires" },
    { value: "CABA", text: "Ciudad Autónoma de Buenos Aires" },
    { value: "Catamarca", text: "Catamarca" },
    { value: "Chaco", text: "Chaco" },
    { value: "Chubut", text: "Chubut" },
    { value: "Córdoba", text: "Córdoba" },
    { value: "Corrientes", text: "Corrientes" },
    { value: "Entre Ríos", text: "Entre Ríos" },
    { value: "Formosa", text: "Formosa" },
    { value: "Jujuy", text: "Jujuy" },
    { value: "La Pampa", text: "La Pampa" },
    { value: "La Rioja", text: "La Rioja" },
    { value: "Mendoza", text: "Mendoza" },
    { value: "Misiones", text: "Misiones" },
    { value: "Neuquén", text: "Neuquén" },
    { value: "Río Negro", text: "Río Negro" },
    { value: "Salta", text: "Salta" },
    { value: "San Juan", text: "San Juan" },
    { value: "San Luis", text: "San Luis" },
    { value: "Santa Cruz", text: "Santa Cruz" },
    { value: "Santa Fe", text: "Santa Fe" },
    { value: "Santiago del Estero", text: "Santiago del Estero" },
    { value: "Tierra del Fuego", text: "Tierra del Fuego" },
    { value: "Tucumán", text: "Tucumán" },
  ],
  Canada: [
    { value: "AB", text: "Alberta" },
    { value: "BC", text: "British Columbia" },
    { value: "MB", text: "Manitoba" },
    { value: "NB", text: "New Brunswick" },
    { value: "NL", text: "Newfoundland and Labrador" },
    { value: "NS", text: "Nova Scotia" },
    { value: "NT", text: "Northwest Territories" },
    { value: "NU", text: "Nunavut" },
    { value: "ON", text: "Ontario" },
    { value: "PE", text: "Prince Edward Island" },
    { value: "QC", text: "Quebec" },
    { value: "SK", text: "Saskatchewan" },
    { value: "YT", text: "Yukon" },
  ],
  Chile: [
    { value: "Arica y Parinacota", text: "Arica y Parinacota" },
    { value: "Tarapacá", text: "Tarapacá" },
    { value: "Antofagasta", text: "Antofagasta" },
    { value: "Atacama", text: "Atacama" },
    { value: "Coquimbo", text: "Coquimbo" },
    { value: "Valparaíso", text: "Valparaíso" },
    { value: "Metropolitana de Santiago", text: "Metropolitana de Santiago" },
    { value: "O'Higgins", text: "O'Higgins" },
    { value: "Maule", text: "Maule" },
    { value: "Ñuble", text: "Ñuble" },
    { value: "Biobío", text: "Biobío" },
    { value: "La Araucanía", text: "La Araucanía" },
    { value: "Los Ríos", text: "Los Ríos" },
    { value: "Los Lagos", text: "Los Lagos" },
    { value: "Aysén", text: "Aysén" },
    { value: "Magallanes", text: "Magallanes" },
  ],
  Colombia: [
    { value: "Amazonas", text: "Amazonas" },
    { value: "Antioquia", text: "Antioquia" },
    { value: "Arauca", text: "Arauca" },
    { value: "Atlántico", text: "Atlántico" },
    { value: "Bolívar", text: "Bolívar" },
    { value: "Boyacá", text: "Boyacá" },
    { value: "Caldas", text: "Caldas" },
    { value: "Caquetá", text: "Caquetá" },
    { value: "Casanare", text: "Casanare" },
    { value: "Cauca", text: "Cauca" },
    { value: "Cesar", text: "Cesar" },
    { value: "Chocó", text: "Chocó" },
    { value: "Córdoba", text: "Córdoba" },
    { value: "Cundinamarca", text: "Cundinamarca" },
    { value: "Guainía", text: "Guainía" },
    { value: "Guaviare", text: "Guaviare" },
    { value: "Huila", text: "Huila" },
    { value: "La Guajira", text: "La Guajira" },
    { value: "Magdalena", text: "Magdalena" },
    { value: "Meta", text: "Meta" },
    { value: "Nariño", text: "Nariño" },
    { value: "Norte de Santander", text: "Norte de Santander" },
    { value: "Putumayo", text: "Putumayo" },
    { value: "Quindío", text: "Quindío" },
    { value: "Risaralda", text: "Risaralda" },
    { value: "San Andrés y Providencia", text: "San Andrés y Providencia" },
    { value: "Santander", text: "Santander" },
    { value: "Sucre", text: "Sucre" },
    { value: "Tolima", text: "Tolima" },
    { value: "Valle del Cauca", text: "Valle del Cauca" },
    { value: "Vaupés", text: "Vaupés" },
    { value: "Vichada", text: "Vichada" },
    { value: "Bogotá D.C.", text: "Bogotá D.C." },
  ],
  Mexico: [
    { value: "Aguascalientes", text: "Aguascalientes" },
    { value: "Baja California", text: "Baja California" },
    { value: "Baja California Sur", text: "Baja California Sur" },
    { value: "Campeche", text: "Campeche" },
    { value: "Chiapas", text: "Chiapas" },
    { value: "Chihuahua", text: "Chihuahua" },
    { value: "Coahuila", text: "Coahuila" },
    { value: "Colima", text: "Colima" },
    { value: "Durango", text: "Durango" },
    { value: "Guanajuato", text: "Guanajuato" },
    { value: "Guerrero", text: "Guerrero" },
    { value: "Hidalgo", text: "Hidalgo" },
    { value: "Jalisco", text: "Jalisco" },
    { value: "México", text: "México" },
    { value: "Michoacán", text: "Michoacán" },
    { value: "Morelos", text: "Morelos" },
    { value: "Nayarit", text: "Nayarit" },
    { value: "Nuevo León", text: "Nuevo León" },
    { value: "Oaxaca", text: "Oaxaca" },
    { value: "Puebla", text: "Puebla" },
    { value: "Querétaro", text: "Querétaro" },
    { value: "Quintana Roo", text: "Quintana Roo" },
    { value: "San Luis Potosí", text: "San Luis Potosí" },
    { value: "Sinaloa", text: "Sinaloa" },
    { value: "Sonora", text: "Sonora" },
    { value: "Tabasco", text: "Tabasco" },
    { value: "Tamaulipas", text: "Tamaulipas" },
    { value: "Tlaxcala", text: "Tlaxcala" },
    { value: "Veracruz", text: "Veracruz" },
    { value: "Yucatán", text: "Yucatán" },
    { value: "Zacatecas", text: "Zacatecas" },
    { value: "Ciudad de México", text: "Ciudad de México" },
  ],
  Portugal: [
    { value: "Aveiro", text: "Aveiro" },
    { value: "Beja", text: "Beja" },
    { value: "Braga", text: "Braga" },
    { value: "Bragança", text: "Bragança" },
    { value: "Castelo Branco", text: "Castelo Branco" },
    { value: "Coimbra", text: "Coimbra" },
    { value: "Évora", text: "Évora" },
    { value: "Faro", text: "Faro" },
    { value: "Guarda", text: "Guarda" },
    { value: "Leiria", text: "Leiria" },
    { value: "Lisboa", text: "Lisboa" },
    { value: "Portalegre", text: "Portalegre" },
    { value: "Porto", text: "Porto" },
    { value: "Santarém", text: "Santarém" },
    { value: "Setúbal", text: "Setúbal" },
    { value: "Viana do Castelo", text: "Viana do Castelo" },
    { value: "Vila Real", text: "Vila Real" },
    { value: "Viseu", text: "Viseu" },
    { value: "Açores", text: "Açores" },
    { value: "Madeira", text: "Madeira" },
  ],
  Spain: [
    { value: "Andalucía", text: "Andalucía" },
    { value: "Aragón", text: "Aragón" },
    { value: "Asturias", text: "Asturias" },
    { value: "Islas Baleares", text: "Islas Baleares" },
    { value: "Islas Canarias", text: "Islas Canarias" },
    { value: "Cantabria", text: "Cantabria" },
    { value: "Castilla-La Mancha", text: "Castilla-La Mancha" },
    { value: "Castilla y León", text: "Castilla y León" },
    { value: "Cataluña", text: "Cataluña" },
    { value: "Extremadura", text: "Extremadura" },
    { value: "Galicia", text: "Galicia" },
    { value: "La Rioja", text: "La Rioja" },
    { value: "Comunidad de Madrid", text: "Comunidad de Madrid" },
    { value: "Región de Murcia", text: "Región de Murcia" },
    { value: "Navarra", text: "Navarra" },
    { value: "País Vasco", text: "País Vasco" },
    { value: "Comunidad Valenciana", text: "Comunidad Valenciana" },
    { value: "Ceuta", text: "Ceuta" },
    { value: "Melilla", text: "Melilla" },
  ],
  "United Kingdom": [
    { value: "England", text: "England" },
    { value: "Scotland", text: "Scotland" },
    { value: "Wales", text: "Wales" },
    { value: "Northern Ireland", text: "Northern Ireland" },
  ],
  "United States": [
    { value: "AL", text: "Alabama" },
    { value: "AK", text: "Alaska" },
    { value: "AZ", text: "Arizona" },
    { value: "AR", text: "Arkansas" },
    { value: "CA", text: "California" },
    { value: "CO", text: "Colorado" },
    { value: "CT", text: "Connecticut" },
    { value: "DE", text: "Delaware" },
    { value: "FL", text: "Florida" },
    { value: "GA", text: "Georgia" },
    { value: "HI", text: "Hawaii" },
    { value: "ID", text: "Idaho" },
    { value: "IL", text: "Illinois" },
    { value: "IN", text: "Indiana" },
    { value: "IA", text: "Iowa" },
    { value: "KS", text: "Kansas" },
    { value: "KY", text: "Kentucky" },
    { value: "LA", text: "Louisiana" },
    { value: "ME", text: "Maine" },
    { value: "MD", text: "Maryland" },
    { value: "MA", text: "Massachusetts" },
    { value: "MI", text: "Michigan" },
    { value: "MN", text: "Minnesota" },
    { value: "MS", text: "Mississippi" },
    { value: "MO", text: "Missouri" },
    { value: "MT", text: "Montana" },
    { value: "NE", text: "Nebraska" },
    { value: "NV", text: "Nevada" },
    { value: "NH", text: "New Hampshire" },
    { value: "NJ", text: "New Jersey" },
    { value: "NM", text: "New Mexico" },
    { value: "NY", text: "New York" },
    { value: "NC", text: "North Carolina" },
    { value: "ND", text: "North Dakota" },
    { value: "OH", text: "Ohio" },
    { value: "OK", text: "Oklahoma" },
    { value: "OR", text: "Oregon" },
    { value: "PA", text: "Pennsylvania" },
    { value: "RI", text: "Rhode Island" },
    { value: "SC", text: "South Carolina" },
    { value: "SD", text: "South Dakota" },
    { value: "TN", text: "Tennessee" },
    { value: "TX", text: "Texas" },
    { value: "UT", text: "Utah" },
    { value: "VT", text: "Vermont" },
    { value: "VA", text: "Virginia" },
    { value: "WA", text: "Washington" },
    { value: "WV", text: "West Virginia" },
    { value: "WI", text: "Wisconsin" },
    { value: "WY", text: "Wyoming" },
    { value: "DC", text: "District of Columbia" },
  ],
};

export const CITIES_BY_COUNTRY_STATE: Record<string, Record<string, string[]>> = {
  Brazil: {
    AC: ["Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá"],
    AL: ["Maceió", "Arapiraca", "Palmeira dos Índios", "Rio Largo"],
    AP: ["Macapá", "Santana", "Laranjal do Jari"],
    AM: ["Manaus", "Itacoatiara", "Parintins", "Manacapuru", "Coari"],
    BA: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Ilhéus", "Itabuna", "Camaçari", "Jequié"],
    CE: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Sobral", "Maracanaú"],
    DF: ["Brasília", "Ceilândia", "Taguatinga", "Samambaia", "Planaltina"],
    ES: ["Vitória", "Vila Velha", "Serra", "Cariacica", "Cachoeiro de Itapemirim"],
    GO: ["Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde"],
    MA: ["São Luís", "Imperatriz", "Caxias", "Timon"],
    MT: ["Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop"],
    MS: ["Campo Grande", "Dourados", "Três Lagoas", "Corumbá"],
    MG: ["Belo Horizonte", "Contagem", "Uberlândia", "Juiz de Fora", "Betim", "Montes Claros", "Uberaba", "Governador Valadares", "Ipatinga"],
    PA: ["Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal"],
    PB: ["João Pessoa", "Campina Grande", "Patos", "Santa Rita"],
    PR: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel", "Foz do Iguaçu"],
    PE: ["Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru", "Petrolina"],
    PI: ["Teresina", "Parnaíba", "Picos", "Floriano"],
    RJ: ["Rio de Janeiro", "Niterói", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Petrópolis", "Volta Redonda", "Campos dos Goytacazes"],
    RN: ["Natal", "Mossoró", "Parnamirim", "Ceará-Mirim"],
    RS: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria", "Gravataí"],
    RO: ["Porto Velho", "Ji-Paraná", "Vilhena", "Ariquemes"],
    RR: ["Boa Vista", "Rorainópolis", "Caracaraí"],
    SC: ["Florianópolis", "Joinville", "Blumenau", "Itajaí", "Chapecó", "Criciúma"],
    SP: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André", "Osasco", "São José dos Campos", "Sorocaba", "Ribeirão Preto", "Santos", "Diadema", "Jundiaí", "Piracicaba", "Bauru", "Barueri", "Mauá", "Carapicuíba", "Mogi das Cruzes", "Itaquaquecetuba", "Limeira", "Suzano"],
    SE: ["Aracaju", "Nossa Senhora do Socorro", "Lagarto"],
    TO: ["Palmas", "Araguaína", "Gurupi", "Porto Nacional"],
  },
  "United States": {
    CA: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Sacramento"],
    NY: ["New York", "Buffalo", "Rochester", "Syracuse", "Albany"],
    TX: ["Houston", "Dallas", "Austin", "San Antonio", "Fort Worth"],
    FL: ["Miami", "Orlando", "Tampa", "Jacksonville", "Tallahassee"],
  },
  Canada: {
    ON: ["Toronto", "Ottawa", "Mississauga", "Brampton", "Hamilton"],
    QC: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"],
    BC: ["Vancouver", "Surrey", "Burnaby", "Victoria", "Richmond"],
    AB: ["Calgary", "Edmonton", "Red Deer", "Lethbridge"],
  },
  Portugal: {
    Lisboa: ["Lisboa", "Loures", "Oeiras", "Amadora", "Sintra"],
    Porto: ["Porto", "Vila Nova de Gaia", "Matosinhos", "Maia"],
    Setúbal: ["Setúbal", "Almada", "Seixal", "Barreiro"],
    Braga: ["Braga", "Guimarães", "Barcelos"],
    Faro: ["Faro", "Portimão", "Olhão", "Loulé"],
  },
  Spain: {
    "Comunidad de Madrid": ["Madrid", "Alcalá de Henares", "Móstoles", "Getafe", "Fuenlabrada"],
    Cataluña: ["Barcelona", "L'Hospitalet de Llobregat", "Badalona", "Tarragona", "Girona"],
    Andalucía: ["Sevilla", "Málaga", "Córdoba", "Granada", "Cádiz"],
    "Comunidad Valenciana": ["Valencia", "Alicante", "Castellón de la Plana", "Elche"],
  },
  Mexico: {
    "Ciudad de México": ["Ciudad de México"],
    Jalisco: ["Guadalajara", "Zapopan", "Tlaquepaque"],
    "Nuevo León": ["Monterrey", "San Nicolás de los Garza", "Guadalupe"],
    "México": ["Toluca", "Ecatepec de Morelos", "Naucalpan de Juárez"],
    Puebla: ["Puebla", "Tehuacán"],
  },
  Argentina: {
    "Buenos Aires": ["La Plata", "Mar del Plata", "Bahía Blanca", "Tandil"],
    CABA: ["Buenos Aires"],
    Córdoba: ["Córdoba", "Villa Carlos Paz", "Río Cuarto"],
    Mendoza: ["Mendoza", "San Rafael"],
    "Santa Fe": ["Rosario", "Santa Fe"],
  },
  Chile: {
    "Metropolitana de Santiago": ["Santiago", "Puente Alto", "Maipú"],
    Valparaíso: ["Valparaíso", "Viña del Mar"],
    Biobío: ["Concepción", "Talcahuano"],
  },
  Colombia: {
    "Bogotá D.C.": ["Bogotá"],
    Antioquia: ["Medellín", "Bello", "Itagüí"],
    "Valle del Cauca": ["Cali", "Palmira"],
    Atlántico: ["Barranquilla", "Soledad"],
  },
};

function uniqueStrings(items: string[]) {
  const seen = new Set<string>();
  return items.filter((item) => {
    if (seen.has(item)) return false;
    seen.add(item);
    return true;
  });
}

export function getCountryCities(country: string, stateValue?: string, stateName?: string) {
  const normalizedCountry = String(country || "").trim();
  const byCountry = CITIES_BY_COUNTRY_STATE[normalizedCountry] || {};

  if (normalizedCountry === "Brazil") {
    const orderedStateCodes = (STATES_BY_COUNTRY.Brazil || []).map((s) => s.value);
    const ordered = orderedStateCodes.flatMap((code) => byCountry[code] || []);
    const extras = Object.entries(byCountry)
      .filter(([key]) => !orderedStateCodes.includes(key))
      .flatMap(([, value]) => value);
    return uniqueStrings([...ordered, ...extras]);
  }

  const listByCode = stateValue ? (byCountry[String(stateValue).trim()] || []) : [];
  const listByName = stateName ? (byCountry[String(stateName).trim()] || []) : [];
  return uniqueStrings([...listByCode, ...listByName]);
}
