"use client";

import { ChevronLeft } from "lucide-react";
import { useParams, useRouter } from "next/navigation";

type PaymentDetails = {
  id: string;
  petName: string;
  reportName: string;
  amountLabel: string;
  vetName: string;
  vetCrmv: string;
  invoiceDate: string;
  petAvatarUrl: string;
  vetAvatarUrl: string;
};

const PAYMENTS: PaymentDetails[] = [
  {
    id: "1",
    petName: "Wolfy",
    reportName: "Urinalysis Report",
    amountLabel: "R$ 5,00",
    vetName: "Dr. Vet",
    vetCrmv: "CRMV-SP 12345",
    invoiceDate: "15/02/2026",
    petAvatarUrl:
      "https://images.unsplash.com/photo-1552053831-71594a27632d?w=200&h=200&fit=crop&crop=faces",
    vetAvatarUrl:
      "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=200&h=200&fit=crop&crop=faces",
  },
];

export default function Page() {
  const router = useRouter();
  const params = useParams<{ payment_id: string }>();
  const paymentId = params?.payment_id;
  const payment = PAYMENTS.find((p) => p.id === paymentId) ?? PAYMENTS[0];

  return (
    <div className="min-h-screen bg-white">
      <div className="flex items-center justify-between px-4 pt-6">
        <button
          type="button"
          onClick={() => router.back()}
          className="flex h-10 w-10 items-center justify-center rounded-full"
          aria-label="Back"
        >
          <ChevronLeft className="h-6 w-6 text-[#111827]" />
        </button>
        <h1 className="text-[16px] font-medium leading-[20px] text-[#111827]">
          Payment Details
        </h1>
        <div className="h-10 w-10" />
      </div>

      <div className="px-4 pt-5">
        <div className="rounded-[16px] bg-[#F5F6F6] px-4 py-3">
          <div className="flex items-center gap-3">
            <div className="h-[44px] w-[44px] rounded-full bg-[#3F78D8] p-[2px]">
              <img
                src={payment.petAvatarUrl}
                alt={payment.petName}
                className="h-full w-full rounded-full object-cover"
              />
            </div>
            <div className="min-w-0 flex-1">
              <div className="truncate text-[16px] font-medium leading-[20px] text-[#111827]">
                {payment.petName}
              </div>
              <div className="mt-1 truncate text-[13px] leading-[16px] text-[#9AA4AF]">
                {payment.reportName}
              </div>
            </div>
          </div>
        </div>

        <div className="mt-6">
          <div className="text-[20px] font-semibold leading-[24px] text-[#111827]">
            Link Generated
          </div>
          <div className="mt-2 text-[14px] leading-[18px] text-[#9AA4AF]">
            Please proceed to pay to view urinalysis results
          </div>
        </div>

        <div className="mt-4 rounded-[16px] bg-[#EEF4FF] px-5 py-4">
          <div className="text-[14px] leading-[18px] text-[#6B7280]">
            Amount to be paid
          </div>
          <div className="mt-1 text-[36px] font-semibold leading-[40px] tracking-[-0.02em] text-[#3F78D8]">
            {payment.amountLabel}
          </div>
        </div>

        <div className="mt-6 text-[14px] font-medium leading-[18px] text-[#9AA4AF]">
          Generated By
        </div>
        <div className="mt-3 flex items-center gap-3">
          <div className="h-[44px] w-[44px] rounded-full bg-[#F5F6F6] p-[2px]">
            <img
              src={payment.vetAvatarUrl}
              alt={payment.vetName}
              className="h-full w-full rounded-full object-cover"
            />
          </div>
          <div className="min-w-0">
            <div className="text-[16px] font-semibold leading-[20px] text-[#111827]">
              {payment.vetName}
            </div>
            <div className="mt-1 text-[13px] leading-[16px] text-[#9AA4AF]">
              {payment.vetCrmv}
            </div>
          </div>
        </div>

        <div className="mt-5 h-px w-full bg-[#E5E7EB]" />

        <div className="mt-4 text-[14px] font-medium leading-[18px] text-[#9AA4AF]">
          Invoice Date
        </div>
        <div className="mt-2 text-[16px] font-semibold leading-[20px] text-[#111827]">
          {payment.invoiceDate}
        </div>
      </div>

      <div className="mt-10 px-4 pb-[calc(env(safe-area-inset-bottom)+18px)]">
        <button
          type="button"
          onClick={() => router.push(`/Guardian/payment/${encodeURIComponent(payment.id)}/pix`)}
          className="h-[52px] w-full rounded-full bg-[#3F78D8] text-[15px] font-medium text-white"
        >
          Proceed Payment
        </button>
        <button
          type="button"
          onClick={() => router.back()}
          className="mt-4 h-[52px] w-full rounded-full bg-[#F5F6F6] text-[15px] font-medium text-[#9AA4AF]"
        >
          Cancel
        </button>
      </div>
    </div>
  );
}
