 "use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { toast } from "react-toastify";

type PaymentItem = {
  id: string;
  petName: string;
  reportName: string;
  amountLabel: string;
  generatedBy: string;
  date: string;
  petAvatarUrl: string;
};

export default function Page() {
  const [items, setItems] = useState<PaymentItem[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let mounted = true;
    (async () => {
      try {
        setLoading(true);
        const res = await fetch(`/api/payment_links/list_for_guardian?status=pending`);
        const data = await res.json().catch(() => null);
        if (!mounted) return;
        if (!res.ok) {
          toast.error(typeof data?.error === "string" ? data.error : "Failed to load payments");
          return;
        }
        const list: any[] = Array.isArray(data?.items) ? data.items : [];
        const mapped: PaymentItem[] = list.map((it: any) => ({
          id: String(it.id),
          petName: String(it.patient?.name || "N/A"),
          reportName: "Urinalysis Report",
          amountLabel: String(it.amountLabel || ""),
          generatedBy: String(it.veterinarian?.name || "N/A"),
          date:
            typeof it.createdAt === "string" && it.createdAt
              ? new Date(it.createdAt).toLocaleDateString()
              : "",
          petAvatarUrl: String(it.patient?.photo || "https://cdn.pixabay.com/photo/2023/02/18/11/00/icon-7797704_640.png"),
        }));
        setItems(mapped);
      } catch {
        toast.error("Network error");
      } finally {
        if (mounted) setLoading(false);
      }
    })();
    return () => {
      mounted = false;
    };
  }, []);

  return (
    <div className="min-h-scree bg-white px-5 pt-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-[20px] font-semibold leading-[24px] text-[#111827]">
            Payments
          </h1>
          <p className="mt-2 text-[14px] leading-[18px] text-[#9AA4AF]">
            Pay the links generated by vets for your pet’s exam
          </p>
        </div>
        <Link
          href="/Guardian/payment/history"
          className="text-[14px] font-medium leading-[18px] text-[#3F78D8]"
        >
          History
        </Link>
      </div>

      <div className="mt-6">
        <div className="text-[14px] font-medium leading-[18px] text-[#9AA4AF]">
          Today
        </div>

        <div className="mt-3 space-y-3">
          {loading ? (
            <div className="text-[14px] leading-[18px] text-[#9AA4AF]">Loading...</div>
          ) : items.length === 0 ? (
            <div className="text-[14px] leading-[18px] text-[#9AA4AF]">No payments to show.</div>
          ) : (
            items.map((item) => (
            <Link
              key={item.id}
              href={`/Guardian/payment/${encodeURIComponent(item.id)}`}
              className="block"
            >
              <div className="rounded-[16px] bg-[#F5F6F6] px-4 py-4">
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="text-[16px] font-medium leading-[20px] text-[#111827]">
                      {item.petName}
                    </div>
                    <div className="mt-1 text-[13px] leading-[16px] text-[#9AA4AF]">
                      {item.reportName}
                    </div>

                    <div className="mt-3 text-[40px] font-semibold leading-[44px] tracking-[-0.02em] text-[#3F78D8]">
                      {item.amountLabel}
                    </div>

                    <div className="mt-3 flex items-center justify-between gap-3">
                      <div className="truncate text-[13px] leading-[16px] text-[#9AA4AF]">
                        Generated by {item.generatedBy}
                      </div>
                      <div className="shrink-0 text-[13px] leading-[16px] text-[#9AA4AF]">
                        {item.date}
                      </div>
                    </div>
                  </div>

                  <div className="shrink-0">
                    <div className="h-[44px] w-[44px] rounded-full bg-[#3F78D8] p-[2px]">
                      <img
                        src={item.petAvatarUrl}
                        alt={item.petName}
                        className="h-full w-full rounded-full object-cover"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </Link>
            ))
          )}
        </div>
      </div>
    </div>
  );
}
