import Link from "next/link";

type PaymentItem = {
  id: string;
  petName: string;
  reportName: string;
  amountLabel: string;
  generatedBy: string;
  date: string;
  petAvatarUrl: string;
};

const PAYMENTS_TODAY: PaymentItem[] = [
  {
    id: "1",
    petName: "Wolfy",
    reportName: "Urinalysis Report",
    amountLabel: "R$ 5,00",
    generatedBy: "Dr Vet",
    date: "15/02/2026",
    petAvatarUrl:
      "https://images.unsplash.com/photo-1552053831-71594a27632d?w=200&h=200&fit=crop&crop=faces",
  },
];

export default function Page() {
  return (
    <div className="min-h-screen bg-white px-5 pt-8">
      <div className="flex items-start justify-between">
        <div>
          <h1 className="text-[20px] font-semibold leading-[24px] text-[#111827]">
            Payments
          </h1>
          <p className="mt-2 text-[14px] leading-[18px] text-[#9AA4AF]">
            Pay the links generated by vets for your pet’s exam
          </p>
        </div>
        <Link
          href="/Guardian/payment/history"
          className="text-[14px] font-medium leading-[18px] text-[#3F78D8]"
        >
          History
        </Link>
      </div>

      <div className="mt-6">
        <div className="text-[14px] font-medium leading-[18px] text-[#9AA4AF]">
          Today
        </div>

        <div className="mt-3 space-y-3">
          {PAYMENTS_TODAY.map((item) => (
            <Link
              key={item.id}
              href={`/Guardian/payment/${encodeURIComponent(item.id)}`}
              className="block"
            >
              <div className="rounded-[16px] bg-[#F5F6F6] px-4 py-4">
                <div className="flex items-start justify-between gap-4">
                  <div className="min-w-0 flex-1">
                    <div className="text-[16px] font-medium leading-[20px] text-[#111827]">
                      {item.petName}
                    </div>
                    <div className="mt-1 text-[13px] leading-[16px] text-[#9AA4AF]">
                      {item.reportName}
                    </div>

                    <div className="mt-3 text-[40px] font-semibold leading-[44px] tracking-[-0.02em] text-[#3F78D8]">
                      {item.amountLabel}
                    </div>

                    <div className="mt-3 flex items-center justify-between gap-3">
                      <div className="truncate text-[13px] leading-[16px] text-[#9AA4AF]">
                        Generated by {item.generatedBy}
                      </div>
                      <div className="shrink-0 text-[13px] leading-[16px] text-[#9AA4AF]">
                        {item.date}
                      </div>
                    </div>
                  </div>

                  <div className="shrink-0">
                    <div className="h-[44px] w-[44px] rounded-full bg-[#3F78D8] p-[2px]">
                      <img
                        src={item.petAvatarUrl}
                        alt={item.petName}
                        className="h-full w-full rounded-full object-cover"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </div>
    </div>
  );
}
